//entry 
//import-ujapi! common.j
//import MainPart.as


array<unit> g_VK(12);
array<unit> g_VisionGiver(12);
array<unit> g_HeroTaker(12);
array<unit> g_HeroTaker2(12);
array<float> PlayerPickerPointX(12);
array<float> PlayerPickerPointY(12);

#include "MainPart.as"

void config() {
    Jass::SetMapName("TRIGSTR_001");
    Jass::SetMapDescription("TRIGSTR_000");
    Jass::SetPlayers(12);
    Jass::SetTeams(2);
    Jass::SetGamePlacement(Jass::MAP_PLACEMENT_USE_MAP_SETTINGS);
    Jass::DefineStartLocation(0, -5056.0, 5248.0);
    Jass::DefineStartLocation(1, -5056.0, 5248.0);
    Jass::DefineStartLocation(2, -5056.0, 5248.0);
    Jass::DefineStartLocation(3, -5056.0, 5248.0);
    Jass::DefineStartLocation(4, -5056.0, 5248.0);
    Jass::DefineStartLocation(5, -5056.0, 5248.0);
    Jass::DefineStartLocation(6, -5056.0, 5248.0);
    Jass::DefineStartLocation(7, -5056.0, 5248.0);
    Jass::DefineStartLocation(8, -5056.0, 5248.0);
    Jass::DefineStartLocation(9, -5056.0, 5248.0);
    Jass::DefineStartLocation(10, -1856.0, 5504.0);
    Jass::DefineStartLocation(11, 6208.0, 4544.0);
    Jass::SetPlayerStartLocation(Jass::Player(0), 0);
    Jass::ForcePlayerStartLocation(Jass::Player(0), 0);
    Jass::SetPlayerColor(Jass::Player(0), Jass::PLAYER_COLOR_RED);
    Jass::SetPlayerRacePreference(Jass::Player(0), Jass::RACE_PREF_ORC);
    Jass::SetPlayerRaceSelectable(Jass::Player(0), false);
    Jass::SetPlayerController(Jass::Player(0), Jass::MAP_CONTROL_USER);
    Jass::SetPlayerStartLocation(Jass::Player(1), 1);
    Jass::SetPlayerColor(Jass::Player(1), Jass::PLAYER_COLOR_BLUE);
    Jass::SetPlayerRacePreference(Jass::Player(1), Jass::RACE_PREF_ORC);
    Jass::SetPlayerRaceSelectable(Jass::Player(1), false);
    Jass::SetPlayerController(Jass::Player(1), Jass::MAP_CONTROL_USER);
    Jass::SetPlayerStartLocation(Jass::Player(2), 2);
    Jass::SetPlayerColor(Jass::Player(2), Jass::PLAYER_COLOR_CYAN);
    Jass::SetPlayerRacePreference(Jass::Player(2), Jass::RACE_PREF_ORC);
    Jass::SetPlayerRaceSelectable(Jass::Player(2), false);
    Jass::SetPlayerController(Jass::Player(2), Jass::MAP_CONTROL_USER);
    Jass::SetPlayerStartLocation(Jass::Player(3), 3);
    Jass::SetPlayerColor(Jass::Player(3), Jass::PLAYER_COLOR_PURPLE);
    Jass::SetPlayerRacePreference(Jass::Player(3), Jass::RACE_PREF_ORC);
    Jass::SetPlayerRaceSelectable(Jass::Player(3), false);
    Jass::SetPlayerController(Jass::Player(3), Jass::MAP_CONTROL_USER);
    Jass::SetPlayerStartLocation(Jass::Player(4), 4);
    Jass::SetPlayerColor(Jass::Player(4), Jass::PLAYER_COLOR_YELLOW);
    Jass::SetPlayerRacePreference(Jass::Player(4), Jass::RACE_PREF_ORC);
    Jass::SetPlayerRaceSelectable(Jass::Player(4), false);
    Jass::SetPlayerController(Jass::Player(4), Jass::MAP_CONTROL_USER);
    Jass::SetPlayerStartLocation(Jass::Player(5), 5);
    Jass::SetPlayerColor(Jass::Player(5), Jass::PLAYER_COLOR_ORANGE);
    Jass::SetPlayerRacePreference(Jass::Player(5), Jass::RACE_PREF_ORC);
    Jass::SetPlayerRaceSelectable(Jass::Player(5), false);
    Jass::SetPlayerController(Jass::Player(5), Jass::MAP_CONTROL_USER);
    Jass::SetPlayerStartLocation(Jass::Player(6), 6);
    Jass::SetPlayerColor(Jass::Player(6), Jass::PLAYER_COLOR_GREEN);
    Jass::SetPlayerRacePreference(Jass::Player(6), Jass::RACE_PREF_ORC);
    Jass::SetPlayerRaceSelectable(Jass::Player(6), false);
    Jass::SetPlayerController(Jass::Player(6), Jass::MAP_CONTROL_USER);
    Jass::SetPlayerStartLocation(Jass::Player(7), 7);
    Jass::SetPlayerColor(Jass::Player(7), Jass::PLAYER_COLOR_PINK);
    Jass::SetPlayerRacePreference(Jass::Player(7), Jass::RACE_PREF_ORC);
    Jass::SetPlayerRaceSelectable(Jass::Player(7), false);
    Jass::SetPlayerController(Jass::Player(7), Jass::MAP_CONTROL_USER);
    Jass::SetPlayerStartLocation(Jass::Player(8), 8);
    Jass::SetPlayerColor(Jass::Player(8), Jass::PLAYER_COLOR_LIGHT_GRAY);
    Jass::SetPlayerRacePreference(Jass::Player(8), Jass::RACE_PREF_ORC);
    Jass::SetPlayerRaceSelectable(Jass::Player(8), false);
    Jass::SetPlayerController(Jass::Player(8), Jass::MAP_CONTROL_USER);
    Jass::SetPlayerStartLocation(Jass::Player(9), 9);
    Jass::SetPlayerColor(Jass::Player(9), Jass::PLAYER_COLOR_LIGHT_BLUE);
    Jass::SetPlayerRacePreference(Jass::Player(9), Jass::RACE_PREF_ORC);
    Jass::SetPlayerRaceSelectable(Jass::Player(9), false);
    Jass::SetPlayerController(Jass::Player(9), Jass::MAP_CONTROL_USER);
    Jass::SetPlayerStartLocation(Jass::Player(10), 10);
    Jass::ForcePlayerStartLocation(Jass::Player(10), 10);
    Jass::SetPlayerColor(Jass::Player(10), Jass::PLAYER_COLOR_AQUA);
    Jass::SetPlayerRacePreference(Jass::Player(10), Jass::RACE_PREF_UNDEAD);
    Jass::SetPlayerRaceSelectable(Jass::Player(10), false);
    Jass::SetPlayerController(Jass::Player(10), Jass::MAP_CONTROL_COMPUTER);
    Jass::SetPlayerStartLocation(Jass::Player(11), 11);
    Jass::ForcePlayerStartLocation(Jass::Player(11), 11);
    Jass::SetPlayerColor(Jass::Player(11), Jass::PLAYER_COLOR_BROWN);
    Jass::SetPlayerRacePreference(Jass::Player(11), Jass::RACE_PREF_UNDEAD);
    Jass::SetPlayerRaceSelectable(Jass::Player(11), false);
    Jass::SetPlayerController(Jass::Player(11), Jass::MAP_CONTROL_COMPUTER);
    Jass::SetPlayerTeam(Jass::Player(0), 0);
    Jass::SetPlayerTeam(Jass::Player(1), 0);
    Jass::SetPlayerTeam(Jass::Player(2), 0);
    Jass::SetPlayerTeam(Jass::Player(3), 0);
    Jass::SetPlayerTeam(Jass::Player(4), 0);
    Jass::SetPlayerTeam(Jass::Player(5), 0);
    Jass::SetPlayerTeam(Jass::Player(6), 0);
    Jass::SetPlayerTeam(Jass::Player(7), 0);
    Jass::SetPlayerTeam(Jass::Player(8), 0);
    Jass::SetPlayerTeam(Jass::Player(9), 0);
    SetPlayerAllianceStateAllyBJ(Jass::Player(0), Jass::Player(1), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(0), Jass::Player(2), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(0), Jass::Player(3), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(0), Jass::Player(4), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(0), Jass::Player(5), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(0), Jass::Player(6), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(0), Jass::Player(7), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(0), Jass::Player(8), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(0), Jass::Player(9), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(1), Jass::Player(0), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(1), Jass::Player(2), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(1), Jass::Player(3), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(1), Jass::Player(4), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(1), Jass::Player(5), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(1), Jass::Player(6), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(1), Jass::Player(7), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(1), Jass::Player(8), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(1), Jass::Player(9), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(2), Jass::Player(0), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(2), Jass::Player(1), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(2), Jass::Player(3), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(2), Jass::Player(4), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(2), Jass::Player(5), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(2), Jass::Player(6), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(2), Jass::Player(7), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(2), Jass::Player(8), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(2), Jass::Player(9), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(3), Jass::Player(0), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(3), Jass::Player(1), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(3), Jass::Player(2), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(3), Jass::Player(4), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(3), Jass::Player(5), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(3), Jass::Player(6), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(3), Jass::Player(7), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(3), Jass::Player(8), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(3), Jass::Player(9), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(4), Jass::Player(0), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(4), Jass::Player(1), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(4), Jass::Player(2), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(4), Jass::Player(3), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(4), Jass::Player(5), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(4), Jass::Player(6), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(4), Jass::Player(7), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(4), Jass::Player(8), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(4), Jass::Player(9), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(5), Jass::Player(0), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(5), Jass::Player(1), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(5), Jass::Player(2), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(5), Jass::Player(3), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(5), Jass::Player(4), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(5), Jass::Player(6), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(5), Jass::Player(7), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(5), Jass::Player(8), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(5), Jass::Player(9), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(6), Jass::Player(0), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(6), Jass::Player(1), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(6), Jass::Player(2), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(6), Jass::Player(3), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(6), Jass::Player(4), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(6), Jass::Player(5), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(6), Jass::Player(7), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(6), Jass::Player(8), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(6), Jass::Player(9), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(7), Jass::Player(0), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(7), Jass::Player(1), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(7), Jass::Player(2), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(7), Jass::Player(3), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(7), Jass::Player(4), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(7), Jass::Player(5), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(7), Jass::Player(6), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(7), Jass::Player(8), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(7), Jass::Player(9), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(8), Jass::Player(0), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(8), Jass::Player(1), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(8), Jass::Player(2), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(8), Jass::Player(3), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(8), Jass::Player(4), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(8), Jass::Player(5), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(8), Jass::Player(6), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(8), Jass::Player(7), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(8), Jass::Player(9), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(9), Jass::Player(0), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(9), Jass::Player(1), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(9), Jass::Player(2), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(9), Jass::Player(3), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(9), Jass::Player(4), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(9), Jass::Player(5), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(9), Jass::Player(6), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(9), Jass::Player(7), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(9), Jass::Player(8), true);
    Jass::SetPlayerTeam(Jass::Player(10), 1);
    Jass::SetPlayerTeam(Jass::Player(11), 1);
    SetPlayerAllianceStateAllyBJ(Jass::Player(10), Jass::Player(11), true);
    SetPlayerAllianceStateAllyBJ(Jass::Player(11), Jass::Player(10), true);
    Jass::SetStartLocPrioCount(0, 9);
    Jass::SetStartLocPrio(0, 0, 1, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(0, 1, 2, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(0, 2, 3, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(0, 3, 4, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(0, 4, 5, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(0, 5, 6, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(0, 6, 7, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(0, 7, 8, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(0, 8, 9, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrioCount(1, 9);
    Jass::SetStartLocPrio(1, 0, 0, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(1, 1, 2, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(1, 2, 3, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(1, 3, 4, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(1, 4, 5, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(1, 5, 6, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(1, 6, 7, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(1, 7, 8, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(1, 8, 9, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrioCount(2, 9);
    Jass::SetStartLocPrio(2, 0, 0, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(2, 1, 1, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(2, 2, 3, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(2, 3, 4, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(2, 4, 5, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(2, 5, 6, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(2, 6, 7, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(2, 7, 8, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(2, 8, 9, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrioCount(3, 9);
    Jass::SetStartLocPrio(3, 0, 0, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(3, 1, 1, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(3, 2, 2, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(3, 3, 4, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(3, 4, 5, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(3, 5, 6, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(3, 6, 7, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(3, 7, 8, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(3, 8, 9, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrioCount(4, 9);
    Jass::SetStartLocPrio(4, 0, 0, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(4, 1, 1, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(4, 2, 2, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(4, 3, 3, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(4, 4, 5, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(4, 5, 6, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(4, 6, 7, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(4, 7, 8, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(4, 8, 9, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrioCount(5, 9);
    Jass::SetStartLocPrio(5, 0, 0, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(5, 1, 1, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(5, 2, 2, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(5, 3, 3, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(5, 4, 4, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(5, 5, 6, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(5, 6, 7, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(5, 7, 8, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(5, 8, 9, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrioCount(6, 9);
    Jass::SetStartLocPrio(6, 0, 0, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(6, 1, 1, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(6, 2, 2, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(6, 3, 3, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(6, 4, 4, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(6, 5, 5, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(6, 6, 7, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(6, 7, 8, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(6, 8, 9, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrioCount(7, 9);
    Jass::SetStartLocPrio(7, 0, 0, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(7, 1, 1, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(7, 2, 2, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(7, 3, 3, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(7, 4, 4, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(7, 5, 5, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(7, 6, 6, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(7, 7, 8, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(7, 8, 9, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrioCount(8, 9);
    Jass::SetStartLocPrio(8, 0, 0, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(8, 1, 1, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(8, 2, 2, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(8, 3, 3, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(8, 4, 4, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(8, 5, 5, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(8, 6, 6, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(8, 7, 7, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(8, 8, 9, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrioCount(9, 9);
    Jass::SetStartLocPrio(9, 0, 0, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(9, 1, 1, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(9, 2, 2, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(9, 3, 3, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(9, 4, 4, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(9, 5, 5, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(9, 6, 6, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(9, 7, 7, Jass::MAP_LOC_PRIO_HIGH);
    Jass::SetStartLocPrio(9, 8, 8, Jass::MAP_LOC_PRIO_HIGH);
}

void SetAmbientDaySound(string inLabel) {
    Jass::CreateMIDISound(inLabel, 20, 20);
}

void SetAmbientNightSound(string inLabel) {
    Jass::CreateMIDISound(inLabel, 20, 20);
}

void SetPlayerAllianceStateAllyBJ(player sourcePlayer, player otherPlayer, bool flag) {
    Jass::SetPlayerAlliance(sourcePlayer, otherPlayer, Jass::ALLIANCE_PASSIVE, flag);
    Jass::SetPlayerAlliance(sourcePlayer, otherPlayer, Jass::ALLIANCE_HELP_REQUEST, flag);
    Jass::SetPlayerAlliance(sourcePlayer, otherPlayer, Jass::ALLIANCE_HELP_RESPONSE, flag);
    Jass::SetPlayerAlliance(sourcePlayer, otherPlayer, Jass::ALLIANCE_SHARED_XP, flag);
    Jass::SetPlayerAlliance(sourcePlayer, otherPlayer, Jass::ALLIANCE_SHARED_SPELLS, flag);
}

void CreateAllDestructables() {
    destructable d;
    Jass::CreateDestructable('DTg3', -6400.0, 5248.0, 0.000, 0.900, 0);
    Jass::CreateDestructableZ('DTsb', 640.0, -5600.0, -180.0, 270.000, 1.000, 0);
    Jass::CreateDestructableZ('DTsb', 2432.0, -5600.0, -192.8, 270.000, 1.000, 0);
    d = Jass::CreateDestructable('Dofw', -2880.0, 5248.0, 0.000, 1.000, 0);
    Jass::KillDestructable(d);
    d = Jass::CreateDestructable('Dofw', -3840.0, 3968.0, 90.000, 1.000, 0);
    Jass::KillDestructable(d);
    d = Jass::CreateDestructable('Dofw', -4608.0, 3968.0, 90.000, 1.000, 0);
    Jass::KillDestructable(d);
    d = nil;
    Jass::CreateDestructableZ('YT06', -5824.0, 5280.0, -96.0, 90.000, 1.000, 0);
    Jass::CreateDestructable('YTpb', -5280.0, 5216.0, 270.000, 1.000, 0);
    Jass::CreateDestructable('YTpb', -5280.0, 5280.0, 270.000, 1.000, 0);
    Jass::CreateDestructable('YTpb', -5280.0, 5344.0, 270.000, 1.000, 0);
    Jass::CreateDestructable('YTpb', -5280.0, 5408.0, 270.000, 1.000, 0);
    Jass::CreateDestructable('YTpb', -5280.0, 5152.0, 270.000, 1.000, 0);
}

void main() {
    Jass::SetCameraBounds(- 7296.0 + Jass::GetCameraMargin(CAMERA_MARGIN_LEFT), - 7424.0 + Jass::GetCameraMargin(CAMERA_MARGIN_BOTTOM), 16128.0 - Jass::GetCameraMargin(CAMERA_MARGIN_RIGHT), 7296.0 - Jass::GetCameraMargin(CAMERA_MARGIN_TOP), - 7296.0 + Jass::GetCameraMargin(CAMERA_MARGIN_LEFT), 7296.0 - Jass::GetCameraMargin(CAMERA_MARGIN_TOP), 16128.0 - Jass::GetCameraMargin(CAMERA_MARGIN_RIGHT), - 7424.0 + Jass::GetCameraMargin(CAMERA_MARGIN_BOTTOM));
    Jass::SetWaterBaseColor(64, 64, 64, 255);
    Jass::NewSoundEnvironment("Dungeon");
    SetAmbientDaySound("DungeonDay");
    SetAmbientNightSound("DungeonNight");
    Jass::SetMapMusic("Music", true, 0);
    CreateAllDestructables();
    Jass::SetDayNightModels("Environment\\DNC\\DNCDalaran\\DNCDalaranTerrain\\DNCDalaranTerrain.mdl", "Environment\\DNC\\DNCDalaran\\DNCDalaranUnit\\DNCDalaranUnit.mdl");
    
    Jass::CreateUnit(Jass::Player(15), 'h085', -7232.0, 5312.0, 270.000);
    Jass::CreateUnit(Jass::Player(15), 'h00F', -6512.6, 5159.5, 35.774);
    Jass::CreateUnit(Jass::Player(15), 'n00B', -6528.0, 6592.0, 270.000);
    Jass::CreateUnit(Jass::Player(15), 'h08A', -7168.0, 5056.0, 270.000);

    g_VK[0] = Jass::CreateUnit(Jass::Player(15), 'h01O', -864.0, 2080.0, 270.000);
    g_VK[1] = Jass::CreateUnit(Jass::Player(15), 'h01O', 3872.0, 2016.0, 270.000);
    Jass::CreateUnit(Jass::Player(11), 'h02A', -7167.9, 5051.3, 131.460);
    Jass::CreateUnit(Jass::Player(15), 'n078', -6483.3, 5246.0, 216.463);
    Jass::CreateUnit(Jass::Player(15), 'h087', -6657.4, 4404.0, 155.630);
    Jass::CreateUnit(Jass::Player(15), 'n079', -7035.6, 4930.1, 270.000);
    Jass::CreateUnit(Jass::Player(15), 'h08B', -7168.0, 4864.0, 270.000);
    Jass::CreateUnit(Jass::Player(15), 'n075', -7025.0, 6261.8, 270.000);
    g_VK[2] = Jass::CreateUnit(Jass::Player(15), 'h01O', 10336.0, 2080.0, 270.000);
    g_VK[3] = Jass::CreateUnit(Jass::Player(15), 'h01O', 14432.0, 4256.0, 270.000);
    g_VK[4] = Jass::CreateUnit(Jass::Player(15), 'h01O', 11360.0, -864.0, 270.000);

    
    g_HeroTaker2[0] = Jass::CreateUnit(Jass::Player(0), 'h08F', -6629.3, 6885.0,  92.870);
    PlayerPickerPointX[0] = -6629.3;
    PlayerPickerPointY[0] = 6885.0;
    g_HeroTaker2[1] = Jass::CreateUnit(Jass::Player(1), 'h08F', -6595.7, 6935.1, 358.040);
    PlayerPickerPointX[1] = -6595.7;
    PlayerPickerPointY[1] = 6935.1;
    g_HeroTaker2[2] = Jass::CreateUnit(Jass::Player(2), 'h08F', -6543.0, 6961.7,   4.780);
    PlayerPickerPointX[2] = -6543.0;
    PlayerPickerPointY[2] = 6961.7;
    g_HeroTaker2[3] = Jass::CreateUnit(Jass::Player(3), 'h08F', -6483.2, 6951.0, 286.280);
    PlayerPickerPointX[3] = -6483.2;
    PlayerPickerPointY[3] = 6951.0;
    g_HeroTaker2[4] = Jass::CreateUnit(Jass::Player(4), 'h08F', -6437.5, 6907.1, 145.840);
    PlayerPickerPointX[4] = -6437.5;
    PlayerPickerPointY[4] = 6907.1;
    g_HeroTaker2[5] = Jass::CreateUnit(Jass::Player(5), 'h08F', -6425.7, 6840.7, 190.110);
    PlayerPickerPointX[5] = -6425.7;
    PlayerPickerPointY[5] = 6840.7;
    g_HeroTaker2[6] = Jass::CreateUnit(Jass::Player(6), 'h08F', -6448.5, 6789.1, 146.110);
    PlayerPickerPointX[6] = -6448.5;
    PlayerPickerPointY[6] = 6789.1;
    g_HeroTaker2[7] = Jass::CreateUnit(Jass::Player(7), 'h08F', -6508.4, 6758.9, 301.550);
    PlayerPickerPointX[7] = -6508.4;
    PlayerPickerPointY[7] = 6758.9;
    g_HeroTaker2[8] = Jass::CreateUnit(Jass::Player(8), 'h08F', -6577.7, 6766.5, 301.730);
    PlayerPickerPointX[8] = -6577.7;
    PlayerPickerPointY[8] = 6766.5;
    g_HeroTaker2[9] = Jass::CreateUnit(Jass::Player(9), 'h08F', -6628.4, 6815.7,  50.340);
    PlayerPickerPointX[9] = -6628.4;
    PlayerPickerPointY[9] = 6815.7;

    g_HeroTaker[0] = Jass::CreateUnit(Jass::Player(0), 'h088', -6529.1, 6851.9, 119.661);
    g_HeroTaker[1] = Jass::CreateUnit(Jass::Player(1), 'h088', -6505.9, 6824.7, 123.129);
    g_HeroTaker[2] = Jass::CreateUnit(Jass::Player(2), 'h088', -6558.2, 6865.8, 327.025);
    g_HeroTaker[3] = Jass::CreateUnit(Jass::Player(3), 'h088', -6535.9, 6862.8, 318.274);
    g_HeroTaker[4] = Jass::CreateUnit(Jass::Player(4), 'h088', -6544.3, 6862.9,  43.832);
    g_HeroTaker[5] = Jass::CreateUnit(Jass::Player(5), 'h088', -6499.7, 6851.1, 180.701);
    g_HeroTaker[6] = Jass::CreateUnit(Jass::Player(6), 'h088', -6537.8, 6856.2,  66.734);
    g_HeroTaker[7] = Jass::CreateUnit(Jass::Player(7), 'h088', -6519.2, 6854.1, 293.624);
    g_HeroTaker[8] = Jass::CreateUnit(Jass::Player(8), 'h088', -6531.7, 6842.1, 330.790);
    g_HeroTaker[9] = Jass::CreateUnit(Jass::Player(9), 'h088', -6522.0, 6857.0, 217.781);

    g_VisionGiver[0] = Jass::CreateUnit(Jass::Player(0), 'h08C', -6892.8, 5274.1,  25.511);
    g_VisionGiver[1] = Jass::CreateUnit(Jass::Player(0), 'h08C', -6329.2, 6492.6, 295.816);
    g_VisionGiver[2] = Jass::CreateUnit(Jass::Player(0), 'h08C', -6891.8, 5958.0, 270.272);
    g_VisionGiver[3] = Jass::CreateUnit(Jass::Player(0), 'h08C', -6889.3, 4479.2,  98.957);
    g_VisionGiver[4] = Jass::CreateUnit(Jass::Player(0), 'h08C', -6937.6, 6887.9, 295.816);

    Jass::SetUnitInvulnerable(Jass::CreateUnit(Jass::Player(15), 'IIII', -1482.3, 1472.1, 0.000), true);
    Jass::SetUnitInvulnerable(Jass::CreateUnit(Jass::Player(15), 'IIll', -1483.9, 2252.0, 0.000), true);
    Jass::SetUnitInvulnerable(Jass::CreateUnit(Jass::Player(15), 'h036', -1457.0, 2669.3, 136.092), true);
    Jass::SetUnitInvulnerable(Jass::CreateUnit(Jass::Player(15), 'h035', -1436.3, 1746.6, 300.430), true);
    Jass::SetUnitInvulnerable(Jass::CreateUnit(Jass::Player(15), 'h03C', -1288.0, 1453.9, 78.104), true);
    
    g_VK[5] = Jass::CreateUnit(Jass::Player(15), 'h01O', -4064.0, -2592.0, 270.000);
    g_VK[6] = Jass::CreateUnit(Jass::Player(15), 'h01O', 6560.0, -5344.0, 270.000);
    g_VK[7] = Jass::CreateUnit(Jass::Player(15), 'h01O', 1504.0, -5664.0, 270.000);
    Jass::CreateUnit(Jass::Player(15), 'n073', -7146.4, 5451.7, 215.174);
    Jass::CreateUnit(Jass::Player(15), 'n074', -7127.2, 6052.3, 229.412);
    g_VK[8] = Jass::CreateUnit(Jass::Player(15), 'h01O', -5024.0, 6752.0, 270.000);
    Jass::CreateUnit(Jass::Player(15), 'h00F', -6584.4, 5198.1, 336.963);
    Jass::CreateUnit(Jass::Player(15), 'n076', -7077.3, 5803.3, 270.000);
    Jass::CreateUnit(Jass::Player(15), 'n077', -7070.2, 5336.1, 270.000);
    Jass::CreateUnit(Jass::Player(15), 'h00X', -358.5, 223.2, 222.380);
    MainPart();
}

